- docker-compose.dev.yml
- src/main/java/com/ivory/ivory/controller/ApplyController.java
- src/main/java/com/ivory/ivory/domain/Apply.java
- src/main/java/com/ivory/ivory/domain/Status.java
- src/main/java/com/ivory/ivory/dto/ApplyDetailDto.java
- src/main/java/com/ivory/ivory/dto/ApplyDto.java
- src/main/java/com/ivory/ivory/dto/ApplyListDto.java
- src/main/java/com/ivory/ivory/repository/ApplyRepository.java
- src/main/java/com/ivory/ivory/repository/ChildRepository.java
- src/main/java/com/ivory/ivory/service/ApplyService.java
- src/main/java/com/ivory/ivory/service/ChildService.java
- close #4 
<br>
- 서비스 신청 API 구현
- 서비스 신청 목록 조회 API 구현
- 서비스 신청 세부 조회 API 구현
<br>
1. 서비스 신청
2. 서비스 신청 목록 조회
3. 서비스 신청 세부 조회
<br>
-
> ✨ 서비스 신청 관련 API 구현

- build.gradle
- src/main/java/com/ivory/ivory/config/S3Config.java
- src/main/java/com/ivory/ivory/controller/ChildController.java
- src/main/java/com/ivory/ivory/domain/Child.java
- src/main/java/com/ivory/ivory/dto/ChildListDto.java
- src/main/java/com/ivory/ivory/dto/ChildRequestDto.java
- src/main/java/com/ivory/ivory/s3/S3UploadService.java
- src/main/java/com/ivory/ivory/service/ChildService.java
- src/main/resources/application.yml
- close #5 
- close #6 
<br>
- 자녀 등록 시 성별 받도록 추가
- 자녀 조회 시 성별 반환
- 자녀 등록 시 이미지 업로드 기능 추가
- 자녀 조회 시 이미지도 반환 되도록
<br>
<br>
-
> ✨ 자녀 성별, 이미지 추가

- docker-compose.dev.yml
- src/main/java/com/ivory/ivory/config/DevSecurityConfig.java
- src/main/java/com/ivory/ivory/config/ProdSecurityConfig.java
- close #18 
<br>
-DevSecurityConfig 카카오페이 api 인증관련하여  `.requestMatchers("/api/v1/auth/**","/api/v1/apply/payments/**").permitAll()`로 수정 
- docker-compose에 카카오페이 관련 키 값 환경변수로 추가 
<br>
<br>
-
> ✨ 카카오페이 인증 관련 수정 

- src/main/java/com/ivory/ivory/dto/ChildListDto.java
- src/main/java/com/ivory/ivory/repository/ApplyRepository.java
- src/main/java/com/ivory/ivory/service/ChildService.java
- close #15 
<br>
- dto 수정
- service 로직 수정 
- applyrRepository에 `findFirstByChild_IdOrderByCreateAt`  추가
<br>
<br>
-
> ✨ 자녀 목록 조회 시 최근 신청 현황 반환

- src/main/java/com/ivory/ivory/service/ApplyService.java
- close #21 
<br>
- 신청 내역 조회 시 totalAmount와 subsidy가 db에 저장되어 있는데 불필요하게 또 계산을 하고 반환하도록 코드가 짜여 있어 db에서 바로 가져도록 수정하였습니다. 
<br>
<br>
-
> 🎨 신청 내역 조회 코드 수정

- docker-compose.dev.yml
- src/main/java/com/ivory/ivory/controller/ChildController.java
- src/main/java/com/ivory/ivory/domain/AbsenceCertificate.java
- src/main/java/com/ivory/ivory/dto/AbsenceCertificatePageDto.java
- src/main/java/com/ivory/ivory/dto/AbsenceCertificateRequestDto.java
- src/main/java/com/ivory/ivory/dto/AbsenceCertificateResponseDto.java
- src/main/java/com/ivory/ivory/dto/AbsenceCertificatesDto.java
- src/main/java/com/ivory/ivory/dto/MedicalCertificateResponseDto.java
- src/main/java/com/ivory/ivory/ocr/CertificateOcrParser.java
- src/main/java/com/ivory/ivory/repository/AbsenceCertificateRepository.java
- src/main/java/com/ivory/ivory/service/AbsenceCertificateService.java
- src/main/java/com/ivory/ivory/service/MedicalCertificateService.java
- close #17 
<br>
- 미등원 확인서 업로드 기능 구현
- 미등원 확인서 목록 조회 기능 구현
- 미등원 확인서 세부 조회 기능 구현
<br>
<br>
-
> ✨ 미등원 확인서 관련 기능 구현

- src/main/java/com/ivory/ivory/domain/Apply.java
- src/main/java/com/ivory/ivory/dto/ApplyDetailDto.java
- src/main/java/com/ivory/ivory/dto/ApplyDto.java
- src/main/java/com/ivory/ivory/dto/ApplyListDto.java
- src/main/java/com/ivory/ivory/repository/AbsenceCertificateRepository.java
- src/main/java/com/ivory/ivory/repository/MedicalCertificateRepository.java
- src/main/java/com/ivory/ivory/service/ApplyService.java
- src/main/java/com/ivory/ivory/service/ChildService.java
- close #26 
<br>
- 신청 현황이 없는 경우 반환 String 값 변경
<br>
<br>
-
> 🎨 신청 현황이 없는 경우 반환 String 값 변경

- docker-compose.prod.yml
- src/main/resources/application-dev.yml
- src/main/resources/application-prod.yml
- src/main/resources/application.yml
- close #28 
<br>
-환경변수 및 Docker 배포 설정하였습니다.
<br>
<br>
-
> ✨ 환경변수 및 Docker 배포 설정

- src/main/java/com/ivory/ivory/controller/AuthController.java
- src/main/java/com/ivory/ivory/service/AuthService.java
- close #30 
<br>
- 회원가입 토큰 발급 기능 구현
<br>
<br>
-
> 회원가입 토큰 발급 기능 구현

- src/main/java/com/ivory/ivory/domain/Disease.java
- src/main/java/com/ivory/ivory/domain/MedicalCertificate.java
- src/main/java/com/ivory/ivory/service/MedicalCertificateService.java
- close #32 
<br>
- 진단서 검증 기능 구현
<br>
<br>
-
> ✨ 진단서 검증 기능 구현

- src/main/java/com/ivory/ivory/dto/ApplyListDto.java
- src/main/java/com/ivory/ivory/service/ApplyService.java
- close #이슈번호
<br>
<br>
<br>
-
> 🐛 신청 목록 반환 시 신청 기본키 반환 (#35)

- src/main/java/com/ivory/ivory/dto/ApplyListDto.java
- src/main/java/com/ivory/ivory/dto/ApplyRequestDto.java
- src/main/java/com/ivory/ivory/service/ApplyService.java
> 🐛 신청 api 응답으로 applyId 반환

- .github/workflows/CICD.yml
- src/main/java/com/ivory/ivory/dto/ApplyListDto.java
- src/main/java/com/ivory/ivory/dto/ApplyRequestDto.java
- src/main/java/com/ivory/ivory/repository/AbsenceCertificateRepository.java
- src/main/java/com/ivory/ivory/repository/MedicalCertificateRepository.java
- src/main/java/com/ivory/ivory/service/ApplyService.java
> 🐛 신청 조회 로직 수정 

- .github/workflows/CICD.yml
- src/main/java/com/ivory/ivory/dto/ApplyListDto.java
- src/main/java/com/ivory/ivory/dto/ApplyRequestDto.java
- src/main/java/com/ivory/ivory/repository/AbsenceCertificateRepository.java
- src/main/java/com/ivory/ivory/repository/MedicalCertificateRepository.java
- src/main/java/com/ivory/ivory/service/ApplyService.java
> 🐛 신청 세부 조회 로직 수정 

- src/main/java/com/ivory/ivory/domain/Apply.java
- src/main/java/com/ivory/ivory/service/KakaoPayService.java
> 🎨 카카오페이 approval_url 배포 도메인으로 수정

- src/main/java/com/ivory/ivory/config/DevSecurityConfig.java
- src/main/java/com/ivory/ivory/controller/CaregiverController.java
- src/main/java/com/ivory/ivory/domain/Authority.java
- src/main/java/com/ivory/ivory/domain/Caregiver.java
- src/main/java/com/ivory/ivory/dto/CareListDto.java
- src/main/java/com/ivory/ivory/dto/TokenDto.java
- src/main/java/com/ivory/ivory/init/DataInitializer.java
- src/main/java/com/ivory/ivory/jwt/TokenProvider.java
- src/main/java/com/ivory/ivory/repository/ApplyRepository.java
- src/main/java/com/ivory/ivory/repository/CaregiverRepository.java
- src/main/java/com/ivory/ivory/service/AuthService.java
- src/main/java/com/ivory/ivory/service/CaregiverService.java
- src/main/java/com/ivory/ivory/service/CustomUserDetailsService.java
- close #48 
<br>
- 디폴트로 DB에 들어갈 돌봄이 계정 생성
- 로그인 시 authority 반환
<br>
<br>
-
> ✨ 디폴트 돌보미 계정 생성 

- src/main/java/com/ivory/ivory/controller/CaregiverController.java
- src/main/java/com/ivory/ivory/domain/Apply.java
- src/main/java/com/ivory/ivory/domain/Caregiver.java
- src/main/java/com/ivory/ivory/dto/CareDetailDto.java
- src/main/java/com/ivory/ivory/dto/CareDto.java
- src/main/java/com/ivory/ivory/dto/CareListDto.java
- src/main/java/com/ivory/ivory/repository/ApplyRepository.java
- src/main/java/com/ivory/ivory/service/ApplyService.java
- src/main/java/com/ivory/ivory/service/CaregiverService.java
- close #47 
<br>
- 돌봄 목록 조회 구현
- 돌봄 내용 상세 조회 구현
- 매칭된 돌봄 조회
- 신청 수락 
<br>
<br>
-
> ✨ 돌봄이 관련 API 구현

- src/main/java/com/ivory/ivory/controller/CaregiverController.java
- src/main/java/com/ivory/ivory/repository/ApplyRepository.java
- src/main/java/com/ivory/ivory/service/CaregiverService.java
* 🐛 신청 목록 반환 시 신청 기본키 반환 (#35) (#36)
* 🐛 신청 api 응답으로 applyId 반환 (#39)
* 🐛 신청 목록 반환 시 신청 기본키 반환 (#35)
* 🐛 신청 api 응답으로 applyId 반환 (#38)
* 🐛 신청 목록 반환 시 신청 기본키 반환 (#35) (#36)
* ✨ 신청 API applyId 반환
* 🐛 신청 세부 조회 로직 수정  (#42)
* 🐛 신청 목록 반환 시 신청 기본키 반환 (#35)
* 🐛 신청 api 응답으로 applyId 반환 (#38)
* 🐛 신청 목록 반환 시 신청 기본키 반환 (#35) (#36)
* ✨ 신청 API applyId 반환
* 🐛 신청 조회 로직 수정  (#41)
* 🐛 신청 목록 반환 시 신청 기본키 반환 (#35) (#36)
* 🐛 신청 api 응답으로 applyId 반환 (#39)
* 🐛 신청 목록 반환 시 신청 기본키 반환 (#35)
* 🐛 신청 api 응답으로 applyId 반환 (#38)
* 🐛 신청 목록 반환 시 신청 기본키 반환 (#35) (#36)
* ✨ 신청 API applyId 반환
* 🐛 신청 세부 조회 오류 수정
* 🚀 Cd 파이프라인 수정
* chore: CD 파이프라인 수정
* 🎨 카카오페이 approval_url 배포 도메인으로 수정 (#44)
* 🎨 카카오페이 approval_url 배포 도메인으로 수정
* 🐛 신청 - 서류 연관관계 수정
* ✨ 매칭된 돌봄 초기화 api 구현
---------
- close #이슈번호
<br>
- 간단하게 한 줄로 작성하면 됩니다. (ex. …
> ✨ 매칭된 돌봄 초기화 api 개발 (#58)

- src/main/java/com/ivory/ivory/dto/TokenDto.java
- src/main/java/com/ivory/ivory/repository/ApplyRepository.java
- src/main/java/com/ivory/ivory/service/AuthService.java
- src/main/java/com/ivory/ivory/service/CaregiverService.java
- src/main/java/com/ivory/ivory/service/CustomUserDetailsService.java
> 🎨 로그인 시 member_id 반환

- src/main/java/com/ivory/ivory/repository/ApplyRepository.java
- src/main/java/com/ivory/ivory/service/ApplyService.java
- close #이슈번호
<br>
<br>
<br>
-
> 🎨 학부모ver 신청 목록 최신순 정렬 수정

- src/main/java/com/ivory/ivory/repository/ApplyRepository.java
- src/main/java/com/ivory/ivory/service/ChildService.java
- close #이슈번호
<br>
<br>
<br>
-
> 🎨 자녀 목록 조회 수정

- src/main/java/com/ivory/ivory/service/ChildService.java
- close #이슈번호
<br>
<br>
<br>
-
> 🎨 GetStatus에 돌보미 매칭 추가
